version: '3.1'

services:
  postgres:
    container_name: postgres
    hostname: postgres
    restart: always
    image: volunteer_platform_postgres:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - './data:/var/lib/postgresql/data'
