version: '3.1'

services:
  redis:
    container_name: redis
    hostname: redis
    restart: always
    image: volunteer_platform_redis:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6379:6379'
    volumes:
      - './data:/data'
